// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLWt-usJT2YWAq2hwOiQe1LeCGRKrMKLI',
    appId: '1:373676660614:web:d64dab2ef152635fbbfe07',
    messagingSenderId: '373676660614',
    projectId: 'personal-tracker-9a377',
    authDomain: 'personal-tracker-9a377.firebaseapp.com',
    storageBucket: 'personal-tracker-9a377.appspot.com',
    measurementId: 'G-KF8EBZ9R55',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMsgm3rjYEkO1EOL5wJvv3M8xMBPvCM3Q',
    appId: '1:373676660614:android:4e2117a2b664d94ebbfe07',
    messagingSenderId: '373676660614',
    projectId: 'personal-tracker-9a377',
    storageBucket: 'personal-tracker-9a377.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDejaGvCAP6HvuuxF5ka-czNbqfHdbl-Eg',
    appId: '1:373676660614:ios:70263cb41e2387d7bbfe07',
    messagingSenderId: '373676660614',
    projectId: 'personal-tracker-9a377',
    storageBucket: 'personal-tracker-9a377.appspot.com',
    iosBundleId: 'com.example.personalExpenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDejaGvCAP6HvuuxF5ka-czNbqfHdbl-Eg',
    appId: '1:373676660614:ios:70263cb41e2387d7bbfe07',
    messagingSenderId: '373676660614',
    projectId: 'personal-tracker-9a377',
    storageBucket: 'personal-tracker-9a377.appspot.com',
    iosBundleId: 'com.example.personalExpenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLWt-usJT2YWAq2hwOiQe1LeCGRKrMKLI',
    appId: '1:373676660614:web:9ef1cc6dc592d0c4bbfe07',
    messagingSenderId: '373676660614',
    projectId: 'personal-tracker-9a377',
    authDomain: 'personal-tracker-9a377.firebaseapp.com',
    storageBucket: 'personal-tracker-9a377.appspot.com',
    measurementId: 'G-3KJZ7BP5LX',
  );
}
